# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull agustinheraclio/testing-infra:123
      - name: Run Docker image
        run: sudo docker run -d -p 3000:3000 agustinheraclio/testing-infra:123
