# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-run:
    runs-on: self-hosted
    steps:
      - name: Run Docker image as service
        run:  | 
        sudo su
        docker service create -d -p 3000:3000 agustinheraclio/testing-infra:123